### ISSUE TITLE
Error macro has not been expanded in Scala 2.13.0

### ISSUE THREAD

**Issue by vilu** [propensive/contextual#54]
```
package com.mobimeo.ticketissuer.primitives

import contextual._

object Test  {
  val NonEmptyString = NonEmptyStringModule.Instance
  type NonEmptyString = NonEmptyString.Type

  sealed abstract class NonEmptyStringModule {
    type Type <: String

    def apply(string: String): Option[NonEmptyString] =
      NonEmptyStringParser.check(string).toOption
  }

  object NonEmptyStringModule {
    val Instance: NonEmptyStringModule = new NonEmptyStringModule {
      type Type = String
    }
  }

  object NonEmptyStringParser extends Verifier[NonEmptyString] {
    def check(string: String): Either[(Int, String), NonEmptyString] =
      if (string.isEmpty()) Left(0 -> "string must not be empty") else Right(string.asInstanceOf[NonEmptyString])
  }

  implicit class NonEmptyStringContext(sc: StringContext) {
    val n = Prefix(NonEmptyStringParser, sc)
  }

  n"foo"

}
```

This gives me an `Error:(31, 3) macro has not been expanded
  n"foo"`

It did work in Scala 2.12.x

**Comment by henricook** [comment]
If it helps i'll offer a $50 bug bounty for this to be resolved

**Comment by mblaze** [comment]
Did you figure out a workaround or pinpointed what causes the macro to not expand?

**Comment by som-snytt** [comment]
This must be due to the stabilizer change, where `q.m()` is rewritten to `val stable = q ; stable.m()` to bring parts of the stable type into implicit scope. I'll take a further look, because I already took a whack at stabilization issues, and I also wanted to learn more about this project. It's been a while since I hacked on macros. It's like Crisis on Infinite Earths, where everything you know or could imagine is about to be obliterated and replaced with something unimaginable, something void of imagination. Can one heroic act make a difference?

If the problem is the tree shape, why doesn't the f-interpolator fail?
